### ISSUE TITLE
what file (OTA or IPSW) to download?

### ISSUE THREAD

**Issue by yeahman45** [MatthewPierson/Vieux#80]
i want to upgrade my ipad air to ios 10 (not 12) but ios 10 is nomore signed... what do I need to download? the IOS 10.3.3 ipsw file or the OTA zip?  https://ipsw.me/iPad4,1

**Comment by gillhash** [comment]
@yeahman45  It is always ipsw file which is needed for software upgrade through iTunes but as you noted iOS 10.3.3 is not signed anymore. So 10.3.3 ipsw file would not be of much use unless you are jailbroken and saved shsh of 10.3.3. Chech reddit for that.

**Comment by yeahman45** [comment]
I am jailbroken but i don't have a saved shsh of 10.3.3....can i still upgrade using vieux?

**Comment by MatthewPierson** [comment]
You can use Vieux without SHSH, it saves currently signed OTA blobs for 10.3.3. You use the 10.3.3 IPSW from ipsw.me, not the OTA zip.

**Comment by yeahman45** [comment]
"it saves currently signed OTA blobs for 10.3.3."
what does that mean? I don't have any signed OTA blobs for 10.3.3
Can I use/flash the ipsw iso 10.3.3 (unsigned) found on https://ipsw.me/iPad4,1?

**Comment by MatthewPierson** [comment]
It means what it says. You don't need previously saved blobs, just download the IPSW and run the tool as instructed

**Comment by gillhash** [comment]
@yeahman45  It is always ipsw file which is needed for firmware upgrade through iTunes but as you correctly noted iOS 10.3.3 is not signed anymore, only 12.4.4( or 12.4.5 ipsw file which is released on 28Jan 2020) can be used to upgrade firmware.Downloading 10.3.3 ipsw would be only useful if your ipad air is on jailbreakable ios & has saved 10.3.3 shsh blobs for your device earlier when ios 10.3.3 was sighned. Otherwise you can remain on the old version or update to latest ios 12.4.5 through ipad software update button.

**Comment by gillhash** [comment]
> You can use Vieux without SHSH, it saves currently signed OTA blobs for 10.3.3. You use the 10.3.3 IPSW from ipsw.me, not the OTA zip.

shsh2 blobs are specific & different for each & every single apple device. They are bound to ECID of your device. If you haven't saved them earlier for your ipad air when 10.3.3 was sighned then i am afraid you cannot go to 10.3.3 Without it. Know fully 
 before what you do. if software failed installation failed you will be forced to do latest ios 12.4.5 fresh install & cannot go to ios currently you have. There is no way back and you may lose all your data & jailbreak. So be cautious.

That's why i save shsh blobs for my iPhone & ipad regularly with https://tsssaver.1conan.com/

**Comment by yeahman45** [comment]
lol pretty much conflicting posts... I am confused again now

**Comment by MatthewPierson** [comment]
@gillhash Do you even know what this tool is for????? This tool allows for the use of CURRENTLY SIGNED OTA blobs for 10.3.3, which allow downgrades to 10.3.3 for most A7 devices including the iPad Air 1st gen. @yeahman45 Ignore him he doesn't know what he's talking about, you are able to downgrade your iPad Air 1st gen to 10.3.3 even without previously saved blobs.
